# ===============================
# Stage 1: Build dengan Composer
# ===============================
FROM composer:latest AS builder

WORKDIR /app

# Salin file composer untuk instalasi dependency
COPY composer.json composer.lock ./

COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd bcmath zip exif
RUN docker-php-ext-enable exif

# Install dependency tanpa dev packages dan optimasi autoloader
RUN composer install --no-dev --prefer-dist --no-progress --optimize-autoloader --no-scripts

# Salin seluruh source code aplikasi
COPY . .

# ===============================
# Stage 2: Image Production PHP-FPM
# ===============================
FROM php:8.2.27-fpm-alpine3.21

WORKDIR /var/www

# Install apk packages we want
RUN apk add -Uuv \
    git bash supervisor freetype-dev libjpeg-turbo-dev libzip-dev libpq-dev libexif-dev $PHPIZE_DEPS \
    libpng-dev \
    && rm -rf /var/cache/apk/*

COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions pdo pdo_pgsql opcache pcntl gd bcmath zip exif
RUN docker-php-ext-enable exif

# Setup opcache
# RUN docker-php-ext-configure opcache --enable-opcache
# COPY .docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
    
# Salin hasil composer dari stage builder
COPY --from=builder /app/vendor ./vendor
# COPY .env.example .env

# Salin seluruh source code aplikasi ke image production
COPY --from=builder /app ./

RUN rm -f /var/www/bootstrap/cache/*.php

RUN chown -R www-data:www-data \
    /var/www/storage \
    /var/www/bootstrap/cache

# Set entrypoint untuk menjalankan PHP-FPM
CMD ["php-fpm"]
